---
  - name: USER TOOLS | curl less vim-tiny psmisc
    apt: pkg="{{item}}"
    with_items:
      -  curl 
      -  less 
      -  vim-tiny 
      -  psmisc

  - name: USER TOOLS | ln -s /usr/bin/vim.tiny /usr/bin/vim
    shell: ln -s /usr/bin/vim.tiny /usr/bin/vim

  - name: "SYSTEM SERVICES | Template /sbin/setuser tool runs a command as another user and sets $HOME" 
    template: src="{{role_dir}}/templates/container_init/set_user.j2" dest="/sbin/setuser" mode="u=rwx,g=rx,o=rx"
