---

  # TODO: detect alpine version from container to override default if any

  - name: Alpine Detect version
    shell: cat /etc/alpine-release  | awk 'BEGIN {FS="."}{print $1"."$2}'
    register: alpine_version

  - set_fact:
      container_alpine_version: "{{alpine_version.stdout}}"
      runsvdir_binary: "/sbin/runsvdir"
      sv_binary: "/sbin/sv"
      bin_dir: "/sbin"

  - name: Alpine | Debug - repositories before wiping out
    shell: cat /etc/apk/repositories
    ignore_errors: true

  - name: Alpine | reset /etc/apk/repositories
    copy: content="" dest="/etc/apk/repositories"
    when: container_alpine_version in ["3.4"]

  - name: Alpine | Populate repositories (3.4)
    shell: "echo '{{item}}' >> /etc/apk/repositories"
    with_items:
      - "http://dl-cdn.alpinelinux.org/alpine/v{{container_alpine_version}}/main"
      - "http://dl-cdn.alpinelinux.org/alpine/v{{container_alpine_version}}/community"
      - "http://dl-cdn.alpinelinux.org/alpine/edge/community"
    when: container_alpine_version in ["3.4"]

  - name: Alpine | Update package info if any
    shell: apk update

  - name: Alpine | Debug - repositories after setup
    shell: cat /etc/apk/repositories
    ignore_errors: true
