---

  - name: SYSLOG | Install syslog daemon.
    apt: pkg="syslog-ng-core" state="present"
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: SYSLOG | Install syslog daemon.
    shell: apk add syslog-ng
    when: ansible_distribution in ["Ansible"]

  - name: SYSLOG | Create /etc/service/syslog-ng
    file: path="/etc/service/syslog-ng" state="directory"

  - name: SYSLOG | template /etc/service/syslog-ng/run
    template: src="{{role_dir}}/templates/syslog-ng/syslog-ng.runit.j2" dest="/etc/service/syslog-ng/run" mode="u=rwx,g=rx,o=rx"

  - block:

    - name: "SYSLOG | Template  {{supervisor_confd_path}}/syslog-ng.conf"
      template: src="{{role_dir}}/templates/syslog-ng/syslog-ng.supervisord.j2" dest="{{supervisor_confd_path}}/syslog-ng.conf" mode="u=rw,g=r,o=r"

    when: container_svc == "supervisord"

  - name: SYSLOG | Create /var/lib/syslog-ng
    file: path="/var/lib/syslog-ng" state="directory"

# TODO support Alpine too
  - name: SYSLOG | template /etc/default/syslog-ng
    template: src="{{role_dir}}/templates/syslog-ng/syslog_ng_default.j2" dest="/etc/default/syslog-ng"
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: BOOT | touch /var/log/syslog
    copy: content="" dest="/var/log/syslog" mode="u=rw,g=r,o="

  - name: SYSLOG | ensure /etc/syslog-ng
    file: path="/etc/syslog-ng" state="directory"

  - name: SYSLOG | template /etc/syslog-ng/syslog-ng.conf
    template: src="{{role_dir}}/templates/syslog-ng/syslog-ng.conf.j2" dest="/etc/syslog-ng/syslog-ng.conf"

  - name: SYSLOG | Install syslog to "docker logs" forwarder.
    file: path="/etc/service/syslog-forwarder" state="directory"

  - name: SYSLOG | template /etc/service/syslog-ng/run
    template: src="{{role_dir}}/templates/syslog-ng/syslog-forwarder.runit.j2" dest="/etc/service/syslog-forwarder/run" mode="u=rwx,g=rx,o=rx"

  - block:

    - name: SYSLOG | Template  {{supervisor_confd_path}}/syslog-forwarder.conf
      template: src="{{role_dir}}/templates/syslog-ng/syslog-forwarder.supervisord.j2" dest="{{supervisor_confd_path}}/syslog-forwarder.conf" mode="u=rw,g=r,o=r"

    when: container_svc == "supervisord"

  - name: SYSLOG | Install logrotate.
    apt: pkg="logrotate" state="present"
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: SYSLOG | Install syslog daemon.
    shell: apk add logrotate
    when: ansible_distribution in ["Ansible"]

  - name: SYSLOG | template /etc/syslog-ng/syslog-ng.conf
    template: src="{{role_dir}}/templates/syslog-ng/logrotate.conf.j2" dest="/etc/logrotate.conf"

  - name: SYSLOG | template /etc/logrotate.d/syslog-ng
    template: src="{{role_dir}}/templates/syslog-ng/logrotate_syslogng.j2" dest="/etc/logrotate.d/syslog-ng"
