---
 
  - name: CRON | Installing cron
    package: name="cron" state="present"

  - name: CRON | Creating /etc/service/cron
    file: path="/etc/service/cron" state="directory"

  - name: CRON | Creating /etc/service/cron
    file: path="/etc/crontab" mode="600"

  - name: CRON | Template  /etc/service/cron/run
    template: src="{{role_dir}}/templates/cron/cron.runit.j2" dest="/etc/service/cron/run" mode="u=rwx,g=rx,o=rx"

  - name: CRON | Cron (ubuntu) dirty patch
    shell: sed -i 's/^\s*session\s\+required\s\+pam_loginuid.so/# &/' /etc/pam.d/cron

  - name: CRON | Eliminate N/A items for cron under docker
    file: path="{{item}}" state="absent"
    with_items:
      - /etc/cron.daily/standard 
      - /etc/cron.daily/upstart
      - /etc/cron.daily/dpkg
      - /etc/cron.daily/password
      - /etc/cron.weekly/fstrim

