  - name: SYSTEM SERVICES | Install runit.
    apt: pkg="runit" state="present"
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: SYSTEM SERVICES | Install runit.
    shell: "apk --no-cache add runit{{alpine_custom_repo_tag}}"
    when: ansible_distribution in ["Alpine"]


  - set_fact:
      container_svc_startup_line: "{{bin_dir}}/runsvdir -P /etc/service"
